### PR TITLE
RAHB solution

### PR DESCRIPTION
**Pull request by RichieAHB**
No marching squares or contour finding, just a slightly optimised brute force - who knows if it'll work on the secret test cases.

### CODE REVIEW

**Comment by shtukas** [comment]
Wonderful solution (checked in both browsers):

screen shot 2018-07-13 at 05 28 06

Little detail: your circles should be red (that was a part of the specs), but that is not important. I will correct that for you :)

**Comment by shtukas** [comment]
Circles are now red:

screen shot 2018-07-13 at 05 43 54

**Comment by shtukas** [comment]
Now, you fail one of the test pictures :)

In your folder, I rotated image4.png by 90 degrees anticlockwise. You show:

screen shot 2018-07-13 at 05 46 29

**Comment by RichieAHB** [comment]
@shtukas Just needed to poke x to and y to be at least the radius 🙄

**Comment by RichieAHB** [comment]
@shtukas also I decided that for a tiny bit more area I could lay the circle on the antialiased pixels. Just realised I could probably fix this with `devicePixelRatio` and some scaling and that your original images probably aren’t antialiased ... ah well 😜

**Pull request merged**
